# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppleCoreData' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppleCoreData
    pod 'Alamofire', '~> 4.7'


  target 'AppleCoreDataTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
