# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppsFactoryTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppsFactoryTest
    pod 'Alamofire', '~> 4.7'
    pod 'ObjectMapper'
    pod 'AlamofireObjectMapper'	
    pod 'Kingfisher', '~> 4.0'

  target 'AppsFactoryTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
